[9.4] ESQL: Fix FROM_BASE64 generating wrong non-UTF strings (#155757)
* ESQL: Fix FROM_BASE64 generating wrong non-UTF strings (#154955)

A query like:
```
ROW c = CONTAINS(FROM_BASE64("YfA="), "a")
```

Will break with an error like:
```
java.lang.ArrayIndexOutOfBoundsException: Index 367 out of bounds for length 367
	at org.apache.lucene.util.UnicodeUtil.UTF8toUTF16(UnicodeUtil.java:647)
	at org.apache.lucene.util.BytesRef.utf8ToString(BytesRef.java:139)
	at org.elasticsearch.xpack.esql.expression.function.scalar.string.Contains.process(Contains.java:142)
	at org.elasticsearch.xpack.esql.expression.function.scalar.string.ContainsEvaluator.eval(ContainsEvaluator.java:117)
	at org.elasticsearch.xpack.esql.expression.function.scalar.string.ContainsEvaluator.eval(ContainsEvaluator.java:61)
```

Because all `BytesRef` Keywords/Text are expected to be valid UTF in ESQL, and any call to `BytesRef.utf8ToString()` would break.

`FROM_BASE64` however, can currently output such `BytesRef`s. We don't support yet the `binary` type (Neither the field nor within ESQL). The real solution here would be:
1. Add binary type
2. Make binary->string conversion implicit, following this UTF logic
3. Make `FROM_BASE64` retur nbinary

That would be BWC and make the solution "feature-complete".

* Backport Utf8Sanitizer instead of inlining

* [CI] Auto commit changes from spotless

* Fixed docs

---------

Co-authored-by: elasticsearchmachine <infra-root+elasticsearchmachine@elastic.co>