[ML] fixes inference timeout handling bug that throws unexpected NullPointerException (#87533) (#87604)
The timeout thread was being scheduled to be executed before all the requisite fields were populated. 

This would (usually only in extreme circumstances), would throw a null pointer exception that looked like:

```
2022-06-06T23:40:42,534][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [javaRestTest-2] uncaught exception in thread [elasticsearch[javaRestTest-2][ml_utility][T#4]]
java.lang.NullPointerException: Cannot invoke "org.elasticsearch.xpack.ml.inference.deployment.DeploymentManager$ProcessContext.getTimeoutCount()" because "this.processContext" is null
	at org.elasticsearch.xpack.ml.inference.deployment.AbstractPyTorchAction.onTimeout(AbstractPyTorchAction.java:58) ~[?:?]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:709) ~[elasticsearch-8.4.0-SNAPSHOT.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

This PR fixes this bug and an additional (more minor) bug where inference call rejections were not accurately counted.

closes: https://github.com/elastic/elasticsearch/issues/87457

Co-authored-by: Elastic Machine <elasticmachine@users.noreply.github.com>