[WIP] Upgrade to JUnit 4.12
By curiosity, I was just trying today to upgrade JUnit to 4.12 but this is not straight forward as now the SM is complaining.

```sh
gradle :test:framework:test -Dtests.jvm.argline="-Djava.security.debug=access,failure"
```

```
java.lang.Exception: Stack trace
  2>    at java.lang.Thread.dumpStack(Thread.java:1333)
  2>    at java.security.AccessControlContext.checkPermission(AccessControlContext.java:462)
  2>    at java.security.AccessController.checkPermission(AccessController.java:884)
  2>    at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
  2>    at java.lang.Class.checkMemberAccess(Class.java:2348)
  2>    at java.lang.Class.getDeclaredMethods(Class.java:1974)
  2>    at org.junit.internal.MethodSorter.getDeclaredMethods(MethodSorter.java:54)
  2>    at org.junit.runners.model.TestClass.scanAnnotatedMembers(TestClass.java:65)
  2>    at org.junit.runners.model.TestClass.<init>(TestClass.java:57)
  2>    at com.carrotsearch.randomizedtesting.RandomizedRunner$12.run(RandomizedRunner.java:1053)
  2>    at com.carrotsearch.randomizedtesting.RandomizedRunner$12.run(RandomizedRunner.java:1050)
  2>    at java.security.AccessController.doPrivileged(Native Method)
  2>    at com.carrotsearch.randomizedtesting.RandomizedRunner.getAnnotatedFieldValues(RandomizedRunner.java:1050)
  2>    at com.carrotsearch.randomizedtesting.RandomizedRunner.withClassRules(RandomizedRunner.java:885)
  2>    at com.carrotsearch.randomizedtesting.RandomizedRunner.runSuite(RandomizedRunner.java:674)
  2>    at com.carrotsearch.randomizedtesting.RandomizedRunner.access$200(RandomizedRunner.java:140)
  2>    at com.carrotsearch.randomizedtesting.RandomizedRunner$2.run(RandomizedRunner.java:598)
```

Just opening this PR for now as a WIP.
May be something super easy to fix...