Fix 'autoGeneratedTimestamp should not be set externally' error when retrying IndexRequest (#86184)
We use BulkProcessor to index various features internally (ilm history, watcher history and more).
When an index request is retried then resending that same request can cause the following error:

```
java.lang.IllegalArgumentException: autoGeneratedTimestamp should not be set externally
	at org.elasticsearch.action.bulk.TransportBulkAction.doInternalExecute(TransportBulkAction.java:223) ~[elasticsearch-7.16.1.jar:7.16.1]
	at org.elasticsearch.action.bulk.TransportBulkAction$1.doRun(TransportBulkAction.java:192) ~[elasticsearch-7.16.1.jar:7.16.1]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) [elasticsearch-7.16.1.jar:7.16.1]
	at org.elasticsearch.action.bulk.TransportBulkAction.doExecute(TransportBulkAction.java:200) [elasticsearch-7.16.1.jar:7.16.1]
	at org.elasticsearch.action.bulk.TransportBulkAction.doExecute(TransportBulkAction.java:91) [elasticsearch-7.16.1.jar:7.16.1]
```

This happens when index requests fail because of a retryable error (e.g. EsRejectedExecutionException).
Prior to this change, the BulkProcessor (via Retry) then reuses the same instance.
With this change, the autoGeneratedTimestamp field is unset via a reset method added to IndexRequest class,
which should avoid the IAE.

Closes #83927