Avoid subqueries in from command in snapshot mode
These tests assume support for subqueries in from commands, which is
only enabled in snapshot builds.

Before, tests would fail with
```
ParsingException: line 1:48: no viable alternative at input '('
```