Improve error message in 8.x to 7.x downgrade
In #78638 we introduced a simple mechanism for blocking downgrades from
8.x to 7.x, but the exception message it generates is not very helpful:

    org.elasticsearch.bootstrap.StartupException: ElasticsearchException[failed to bind service]; nested: FileSystemException[{path.data}/nodes/0: Not a directory];

We can't fix earlier 7.x versions to do something better, but this
commit at least means that sufficiently recent 7.x versions will yield a
slightly more helpful message.