Aggs: Fix auto_date_histogram and date_histogram inside a global agg (#147427) (#148831)
Fixes https://github.com/elastic/elasticsearch/issues/92570

This issue was causing wrong query results (See issue) as well as errors like:

```
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 13
at org.elasticsearch.server@9.5.0/org.elasticsearch.common.Rounding$ArrayRounding.round(Rounding.java:1537)
at org.elasticsearch.aggs@9.5.0/org.elasticsearch.aggregations.bucket.histogram.AutoDateHistogramAggregator$FromSingle$2.collect(AutoDateHistogramAggregator.java:273)
at org.elasticsearch.server@9.5.0/org.elasticsearch.search.aggregations.bucket.BucketsAggregator.collectBucket(BucketsAggregator.java:79)
at org.elasticsearch.server@9.5.0/org.elasticsearch.search.aggregations.bucket.filter.FiltersAggregator$SingleFilterLeafCollector.collect(FiltersAggregator.java:384)
at org.elasticsearch.server@9.5.0/org.elasticsearch.search.aggregations.bucket.BucketsAggregator.collectExistingBucket(BucketsAggregator.java:87)
at org.elasticsearch.server@9.5.0/org.elasticsearch.search.aggregations.bucket.global.GlobalAggregator$1.collect(GlobalAggregator.java:54)
```