Update settings.asciidoc
Looks like this has already been removed from 5.0 Alpha 1.  Change heading of this section to "Removed using ..." and note the feature removal in the description?

```
./elasticsearch -Des.node.name=test
starts elasticsearch

Option             Description                           
------             -----------                           
-E <KeyValuePair>  Configure an Elasticsearch setting    
-V, --version      Prints elasticsearch version          
                     information and exits               
-d, --daemonize    Starts Elasticsearch in the background
-h, --help         show help                             
-p, --pidfile      Creates a pid file in the specified   
                     path on start                       
-s, --silent       show minimal output                   
-v, --verbose      show verbose output                   
ERROR: D is not a recognized option
```