Unmute SearchStatesIT::testCanMatch (#115960)
The original failure reported in #108991 seems to be
from a temporary connection failure:

java.net.ConnectException: Connection refused

so we umuting the test.

Closes #108991