ESQL:DS: ORC: fix missing class (#147807)
This fixes the 'java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils' error on Windows.

Closes #147648
Closes #147660

(cherry picked from commit f8c98be3151b277b95ccf4fdafa9590048e9dd72)