Add  Jackson modules to the module-path Server startup has a static dependency on Jackson smile
Fixes issues like:

fatal error in thread [main], exiting
java.lang.NoClassDefFoundError: com/fasterxml/jackson/dataformat/smile/SmileParser
	at elasticsearch.x.content@8.1.0-SNAPSHOT/org.elasticsearch.xcontent.XContentFactory.smileBuilder(XContentFactory.java:55)
	at elasticsearch.x.content@8.1.0-SNAPSHOT/org.elasticsearch.xcontent.XContentFactory.contentBuilder(XContentFactory.java:94)
	at elasticsearch@8.1.0-SNAPSHOT/org.elasticsearch.gateway.PersistedClusterStateService$Writer.makeDocument(PersistedClusterStateService.java:977)
	at elasticsearch@8.1.0-SNAPSHOT/org.elasticsearch.gateway.PersistedClusterStateService$Writer.makeGlobalMetadataDocument(PersistedClusterStateService.java:968)
	at elasticsearch@8.1.0-SNAPSHOT/org.elasticsearch.gateway.PersistedClusterStateService$Writer.addMetadata(PersistedClusterStateService.java:865)
	at elasticsearch@8.1.0-SNAPSHOT/org.elasticsearch.gateway.PersistedClusterStateService$Writer.overwriteMetadata(PersistedClusterStateService.java:856)
	at elasticsearch@8.1.0-SNAPSHOT/org.elasticsearch.gateway.PersistedClusterStateService$Writer.writeFullStateAndCommit(PersistedClusterStateService.java:703)
	at elasticsearch@8.1.0-SNAPSHOT/org.elasticsearch.gateway.GatewayMetaState$LucenePersistedState.<init>(GatewayMetaState.java:444)
	at elasticsearch@8.1.0-SNAPSHOT/org.elasticsearch.gateway.GatewayMetaState.start(GatewayMetaState.java:133)
	at elasticsearch@8.1.0-SNAPSHOT/org.elasticsearch.node.Node.start(Node.java:1129)
	at elasticsearch@8.1.0-SNAPSHOT/org.elasticsearch.bootstrap.Bootstrap.start(Bootstrap.java:272)
	at elasticsearch@8.1.0-SNAPSHOT/org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:367)
	at elasticsearch@8.1.0-SNAPSHOT/org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:166)
	at elasticsearch@8.1.0-SNAPSHOT/org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:157)
	at elasticsearch@8.1.0-SNAPSHOT/org.elasticsearch.common.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:81)
	at elasticsearch.cli@8.1.0-SNAPSHOT/org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:112)
	at elasticsearch.cli@8.1.0-SNAPSHOT/org.elasticsearch.cli.Command.main(Command.java:77)
	at elasticsearch@8.1.0-SNAPSHOT/org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:122)
	at elasticsearch@8.1.0-SNAPSHOT/org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:80)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.dataformat.smile.SmileParser
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 19 more