Do not share Weight between Drivers (#133446)
We have encountered the following error in serverless:

```
java.lang.NullPointerException: Cannot invoke \"org.apache.lucene.search.BulkScorer.score(org.apache.lucene.search.LeafCollector, org.apache.lucene.util.Bits, int, int)\" because \"this.bulkScorer\" is null
at org.elasticsearch.compute.lucene.LuceneOperator$LuceneScorer.scoreNextRange(LuceneOperator.java:233)
at org.elasticsearch.compute.lucene.LuceneSourceOperator.getCheckedOutput(LuceneSourceOperator.java:307)
at org.elasticsearch.compute.lucene.LuceneOperator.getOutput(LuceneOperator.java:143)
at org.elasticsearch.compute.operator.Driver.runSingleLoopIteration(Driver.java:272)
at org.elasticsearch.compute.operator.Driver.run(Driver.java:186)
at org.elasticsearch.compute.operator.Driver$1.doRun(Driver.java:420)
```

I spent considerable time trying to reproduce this issue but was 
unsuccessful, although I understand how it could occur. Weight should
not be shared between threads. Most Weight implementations are safe to
share, but those for term queries (e.g., TermQuery, multi-term queries)
are not, as they contain mutable

This change proposes to stop sharing Weight between Drivers.