Avoid using ExtraFS in StatelessClusterStateCleanupServiceIT (#2440)
See 

```
java.lang.AssertionError: Expected a number as directory name: extra0 |  
-- | --
  | Expected: is <true> |  
  | but: was <false>
```

It is our own test assertion, but I think it makes sense to keep the
assert and avoid the extra files caused by ExtraFS.