attempt to fix PasswordToolsTests by waiting for green health
the failure is caused by .security shards nit being available during
authentication:

```
failed to retrieve password hash for reserved user [elastic]
org.elasticsearch.action.UnavailableShardsException: at least one primary shard for the index [.security-7] is unavailable
```