Update to the latest Azure SDK version.
It's a pain every time as you have manually to update all transitive libs.
So I'm using a maven `pom.xml` like:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>fr.pilato.test.azure</groupId>
    <artifactId>azure-deps</artifactId>
    <version>1.0-SNAPSHOT</version>

    <dependencies>
        <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>azure</artifactId>
            <version>1.4.0</version>
        </dependency>
        <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>azure-mgmt-compute</artifactId>
            <version>1.4.0</version>
        </dependency>
    </dependencies>
</project>
```

And then I'm running:

```sh
mvn dependency:tree
```

To get the full list.

Anyway, this commit is not compiling correctly because of obscure warnings:

```
:plugins:discovery-azure-arm:compileJava - is not incremental (e.g. outputs have changed, no previous execution, etc.).
warning: unknown enum constant SinceVersion.V1_3_0
warning: unknown enum constant SinceVersion.V1_3_0
warning: unknown enum constant SinceVersion.V1_3_0
warning: unknown enum constant SinceVersion.V1_3_0
error: warnings found and -Werror specified
1 error
4 warnings
```