Provide an upgrade path from pre 6.2 to oss
```
centos-7:~$ sudo rpm -i https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.0.rpm
centos-7:~$ rpm -i  /elasticsearch/distribution/packages/oss-rpm/build/distributions/elasticsearch-oss-7.0.0-SNAPSHOT.rpm
error: Failed dependencies:
	elasticsearch < 6.3 is obsoleted by elasticsearch-oss-0:7.0.0_SNAPSHOT-1.noarch
centos-7:~$ rpm -i  /elasticsearch/distribution/packages/oss-rpm/build/distributions/elasticsearch-oss-7.0.0-SNAPSHOT.rpm
error: Failed dependencies:
	elasticsearch < 6.3 is obsoleted by elasticsearch-oss-0:7.0.0_SNAPSHOT-1.noarch
centos-7:~$ sudo rpm -U  /elasticsearch/distribution/packages/oss-rpm/build/distributions/elasticsearch-oss-7.0.0-SNAPSHOT.rpm
 sudo systemctl daemon-reload
 sudo systemctl enable elasticsearch.service
 sudo systemctl start elasticsearch.service
centos-7:~$ sudo rpm -i  /elasticsearch/distribution/packages/rpm/build/distributions/elasticsearch-7.0.0-SNAPSHOT.rpm
error: Failed dependencies:
	elasticsearch-oss conflicts with elasticsearch-0:7.0.0_SNAPSHOT-1.noarch
	elasticsearch >= 6.3 conflicts with (installed) elasticsearch-oss-0:7.0.0_SNAPSHOT-1.noarch
centos-7:~$ sudo rpm -U  /elasticsearch/distribution/packages/rpm/build/distributions/elasticsearch-7.0.0-SNAPSHOT.rpm
error: Failed dependencies:
	elasticsearch-oss conflicts with elasticsearch-0:7.0.0_SNAPSHOT-1.noarch
	elasticsearch >= 6.3 conflicts with (installed) elasticsearch-oss-0:7.0.0_SNAPSHOT-1.noarch
```

```
ubuntu-1804:~$ wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.0.deb
ubuntu-1804:~$ sudo dpkg -i elasticsearch-5.6.0.deb
Selecting previously unselected package elasticsearch.
(Reading database ... 141015 files and directories currently installed.)
Preparing to unpack elasticsearch-5.6.0.deb ...
Creating elasticsearch group... OK
Creating elasticsearch user... OK
Unpacking elasticsearch (5.6.0) ...
Replaced by files in installed package elasticsearch-oss (7.0.0~SNAPSHOT) ...
Setting up elasticsearch (5.6.0) ...
Processing triggers for ureadahead (0.100.0-20) ...
Processing triggers for systemd (237-3ubuntu10.3) ...

ubuntu-1804:~$ sudo  dpkg -i /elasticsearch/distribution/packages/oss-deb/build/distributions/elasticsearch-oss-7.0.0-SNAPSHOT.deb
(Reading database ... 141082 files and directories currently installed.)
Preparing to unpack .../elasticsearch-oss-7.0.0-SNAPSHOT.deb ...
/usr/bin/java
Removing old lib folder
Unpacking elasticsearch-oss (7.0.0~SNAPSHOT) over (7.0.0~SNAPSHOT) ...
Setting up elasticsearch-oss (7.0.0~SNAPSHOT) ...
Created elasticsearch keystore in /etc/elasticsearch
Processing triggers for ureadahead (0.100.0-20) ...
Processing triggers for systemd (237-3ubuntu10.3) ...
```

Closes #36142