ESQL: Unmute test and reuse blockFactory to avoid concurrently modifying the test factories list (#128211)
Fixes https://github.com/elastic/elasticsearch/issues/128092

The error happens inside an ArrayList.add(), and it's a concurrency-related one.

The stacktrace is quite explicative:
```
java.lang.ArrayIndexOutOfBoundsException: Index 34 out of bounds for length 33
at java.util.ArrayList.add(ArrayList.java:485)
at org.elasticsearch.compute.test.ComputeTestCase.blockFactory(ComputeTestCase.java:62)
at org.elasticsearch.compute.aggregation.GroupingAggregatorFunctionTestCase$4$1$1.addBlock(GroupingAggregatorFunctionTestCase.java:659)
```

We were creating new blockFactories() inside the aggregator, which was being called concurrently with different drivers. As `blockFactory()` adds it to a static ArrayList, it was sometimes throwing.

The bug only affects tests. Potentially, all grouping aggregators tests.