Use MappedFieldType.termQuery to generate simple_query_string queries
For Numeric types, if the query's text is passed to create a boolean
query, the 'Long' analyzer can return an exception similar to:

```
IllegalArgumentException: Illegal shift value, must be 0..63; got shift=2147483647
```

This change looks up the `MappedFieldType` for the specified fields (if
available) and uses the `.termQuery` function to create the query from
the string, instead of analyzing it by creating a new boolean query by
default.

Resolves #16577