If there is an un-resolved cluster alert, but there is no .monitoring-es data for this cluster in the last 2 minutes a run time error in the Watcher transform can occur [1]. This could be due some slow down in getting the .monitoring-es data from source cluster to monitoring cluster.
The Watch condition can pass if there are un-resolved alerts, but the
transform assumes there is a cluster state (green,yellow,red) and can
throw an error while trying to read it.

This commit prevents passing the condition if the cluster state was not
found.

Fixes #43184

[1]
```
org.elasticsearch.script.ScriptException: runtime error
	at org.elasticsearch.painless.PainlessScript.convertToScriptException(PainlessScript.java:94) ~[?:?]
	at org.elasticsearch.painless.PainlessScript$Script.execute(ctx.vars.email_recipient = (ctx.payload.kibana_settings.hits.total > 0 && ctx.payload.kibana_settings.hits.hits[0]._source.kibana_settings.xpack != null) ? ctx.payload.kibana_settings.hits.hits[0]._source.kibana_settings.xpack.default_admin_email : null;ct ...:1152) ~[?:?]
	at org.elasticsearch.xpack.watcher.transform.script.ExecutableScriptTransform.doExecute(ExecutableScriptTransform.java:49) ~[x-pack-watcher-7.1.1.jar:7.1.1]
	...
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
```
from .watcher-history:
```
     "type" : "script_exception",
                "reason" : "runtime error",
                "script_stack" : [
                  "java.util.ArrayList.rangeCheck(ArrayList.java:657)",
                  "java.util.ArrayList.get(ArrayList.java:433)",
                  "state = ctx.payload.check.hits.hits[0]._source.cluster_state.status;",
                  "                                   ^---- HERE"
                ],
```