Relax CacheFile.decrementRefCount() assertion (#67633) (#67635)
Some searchable snapshots related tests failed recently on CI for 
Windows platforms (#67579) with the following assertion tripping:

java.lang.AssertionError: fully released cache file should be 
deleted from disk but got [released=true, evicted=true, file not exists=false]
 at __randomizedtesting.SeedInfo.seed([F459F30E820622D8]:0)
  at org.elasticsearch.index.store.cache.CacheFile.assertRefCounted(CacheFile.java:244)
 at org.elasticsearch.index.store.cache.CacheFile.decrementRefCount(CacheFile.java:238)

In #67561 we improved the description of the assertion to show 
more information about the released/evicted/file status. It confirms 
that Files.notExists(file) sometimes returns false on Windows 
platforms. The assertion never tripped on non-Windows platforms
 so far.

The false value does not necessary means that the file exists; this 
value is also returned when the JVM cannot determine the status 
of the file. Since some cache files are evicted soon after the parent's 
directory is deleted (shard was removed from disk) it seems that on 
Windows it is not possible to be sure of the file non-existence.

I think it's simpler to check if the file exists and fails if it's true.

Close #67633