Log a separate message for failure after upload (#1836)
If failure happens after the BCC is uploaded, today we log something
like:

```
failed to upload BCC [3] to object store for unexpected reason
org.elasticsearch.index.IndexNotFoundException: no such index
```

The message is misleading since the upload was actually successful. The
failure is caused by sendNewUploadedCommitNotification failed to locate
the index routing table.

This PR adds a separate logging for failures occured after upload to
improve logging accuracy.