Store: renaming temp files should log errors of delete in trace
The method follows a delete then rename pattern. It currently logs errors in the delete under DEBUG and barfs if the rename fails. It also correctly ignores FileNotFoundException in the first delete round. This protection fails however since lucene uses File.delete() (which is changed in 5.0) so we get a generic IOException in this case. This can result in worrisome  log messages like:

```
[2015-02-28 16:11:42,720][DEBUG][index.store              ] [node_s2] [test][0] failed to delete file [segments_1]
java.io.IOException: Cannot delete .../nodes/2/indices/test/0/index/segments_1
	at org.apache.lucene.store.FSDirectory.deleteFile(FSDirectory.java:272)
````

I also gave the method a better name.