Fix executing missing enrich policy bug. (#80728) (#80754)
When executing a policy that doesn't exist then the execute enrich policy api fails with a NPE:

```
java.lang.NullPointerException: Cannot invoke "org.elasticsearch.xpack.core.enrich.EnrichPolicy.getIndices()" because "this.policy" is null
        at org.elasticsearch.xpack.enrich.EnrichPolicyRunner.run(EnrichPolicyRunner.java:123) ~[?:?]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:712) ~[elasticsearch-8.1.0-SNAPSHOT.jar:8.1.0-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

The error is only visible in the logs and the execute enrich policy API hangs.
What is even worse is that no policies with the same name can be executed, since the policy id is locked.

This fix should address these symptoms and return a 404 in case a policy is being executed that doesn't exist.